apisix:
  node_listen: 9080        # API Gateway entry
  enable_admin: false
  config_center: yaml

routes:
  - uri: /sb/hello
    upstream:
      type: roundrobin
      nodes:
        "springboot:8080": 1
    plugins:
      proxy-rewrite:
        uri: /api/hello

upstreams: []
plugins: []